export const GET_HABITS = "GET_HABITS";
export const REMOVE_HABIT = "REMOVE_HABIT";
export const CREATE_HABIT = "CREATE_HABIT";
export const UPDATE_HABIT = "UPDATE_HABIT";
export const SET_CURRENT_HABIT = "SET_CURRENT_HABIT";
export const CLEAR_CURRENT_HABIT = "CLEAR_CURRENT_HABIT";

export const GET_REWARDS = "GET_REWARDS";
export const REMOVE_REWARD = "REMOVE_REWARD";
export const CREATE_REWARD = "CREATE_REWARD";
export const UPDATE_REWARD = "UPDATE_REWARD";
export const SET_CURRENT_REWARD = "SET_CURRENT_REWARD";
export const LEAR_CURRENT_REWARD = "CLEAR_CURRENT_REWARD";